name: Retype Action for GitHub Pages
author: Object.NET, Inc.
description: |-
  Publishes Retype documentation to GitHub Pages' branch/directory.
inputs:
  branch:
    description: |-
      The name of the target branch where the documentation should be committed
      to. Defaults to "retype"
    required: false
  directory:
    description: |-
      The relative path within the repo/branch where to place the documentation
      files in. Useful if you use the "docs" directory on "main" branch to
      publish the pages. Defaults to root of the branch.
    required: false
  update-branch:
    description: |-
      Set as "true" to push changes straight to the target branch if it already
      exists. This will avoid the need of pull requests or merges when updating
      the documentation. Defaults to "false"/unset.
    required: false
  github-token:
    description: |-
      GitHub Token to use to create pull requests in case a new branch is
      created. If the target branch exists and "update-branch" is not set,
      then a pull request to merge the temporary branch will be created as
      it is pushed to GitHub. If unset, may push a new branch but won't
      create pull requests. Defaults to unset.
    required: false
runs:
  using: "composite"
  steps:
    - run: "${GITHUB_ACTION_PATH}/github.sh"
      shell: bash
      env:
        INPUT_BRANCH: ${{ inputs.branch }}
        INPUT_DIRECTORY: ${{ inputs.directory }}
        INPUT_UPDATE_BRANCH: ${{ inputs.update-branch }}
        INPUT_GITHUB_TOKEN: ${{ inputs.github-token }}